### ISSUE TITLE
Only 1 Viewport shows anything...?

### ISSUE THREAD

**Issue by paulicka** [jocamar/Godot-Common-Game-Framework#2]
I am so excited about this tool...it looks so elegantly designed.  I really appreciate your gift to us all!
I set up a main scene, (almost) exactly duplicating the code in the README#GameManager.
I did NOT set_postprocess_material on the viewport.

When I run, only the upper left quadrant shows anything.
Does this imply that postprocess material handles this?  
I had guessed that thepostprocess material was just for effects...?

It's not critical in anyway, since I don't need multiple viewports at the moment.
I had hoped to duplicate the functionality of the godot demo projects dynamic split screen demo in the future, though.

Any help would be appreciated...
;-)

**Comment by jocamar** [comment]
You don't need to call set_postprocess_material. Are you providing the cameras for the other 3 viewports with set_player_camera?

**Comment by paulicka** [comment]
Yep.  And my PlayerCameraScene has a camera2d in it...I even tried throwing a Camera in there, but that didn't work either.
<img width="1153" alt="Screen Shot 2021-04-17 at 3 09 11 PM" src="https://user-images.githubusercontent.com/105380/115127899-f2a4ef80-9f8e-11eb-8890-e6a18b0d19b0.png">
<img width="1087" alt="Screen Shot 2021-04-17 at 3 10 12 PM" src="https://user-images.githubusercontent.com/105380/115127918-123c1800-9f8f-11eb-87fc-bef150642ff3.png">

**Comment by paulicka** [comment]
By the way, this tool set...it was exactly what I was looking for, and built so well.  I like finding tools that I don't even have the urge to tweak, just extend as intended.  Woot!

**Comment by jocamar** [comment]
Did you end up figuring out what the issue was?

**Comment by paulicka** [comment]
I did not...any thoughts?
I tried GLES3 and GLES2.
I was working on Godot Wild Jam, but that's over now, so I can dive into this in more detail...
Perhaps we could work together on a simple Demo that showcases all the wonderful features of your framework?
;-)

**Comment by jocamar** [comment]
Fixed with https://github.com/jocamar/Godot-Common-Game-Framework/commit/968e55d4bdcc2db626e7a816ba0d0bf771fcaa0d. Let me know if it works for you.

**Comment by paulicka** [comment]
Sweeeeeeet!  Totally works now...!

Is it possible for each viewport to be on different scenes?
It seems that to change levels, I have to:
* Call set_player_camera per player
* Reinstance the camera per player
...even though, looking at set_player_camera, it looks like you check if it is the same camera.
But set_player_camera also check if it is still in the tree.
That's what I meant by a more full demo, because I am not sure how you intend for it to be used, versus how the code is currently implemented.
Yet, jm_game_manager is also managing scenes, which...the player camera scene could be a managed scene, as well.
So why not set_player_camera(player_id, player_camera_scene_id), and set_player_scene(player_id, player_scene_id)?
And jm_game_manager could put them together for you as needed...?
Am I missing something obvious?

**Comment by jocamar** [comment]
Hmm, I think that in that case if you want to persist the cameras through different scenes you could give a different scene_id when adding the cameras, so you'd do:
change_scene(level1, "level1") and set_player_camera(myCam, 1, "cameras")

This way you could call unload_scene("level1") and load your level 2 (additively) and keep the cameras associated with the "cameras" id.

As for different viewports in different scenes, that is not possible at the moment since all camera have their world set to use the main camera's world. But it should be possible to extend it to have that functionality by setting the other viewports to have their own world.
